CREATE TABLE IF NOT EXISTS channels (
    id TEXT NOT NULL PRIMARY KEY,
    last_ts TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS channel_count (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    channel_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    count INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_channel_count_channel_id ON channel_count(channel_id);
CREATE INDEX IF NOT EXISTS idx_channel_count_count ON channel_count(count DESC);
